.TH "acknowledge" 3 "9 Nov 2002" "JsUnit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
acknowledge \- Acknowledgements
.PP
JsUnit would not have been possible in this form without the work and ideas of a lot of other people:
.PP
.TP
Dimitri van Heesch for his wonderful documentation tool Doxygen
.PP
.TP
BerliOS for hosting this project
.PP
.TP
Achim Kraus, author of the first Perl script converting the JavaScript code into something Doxygen can understand
.PP
.TP
People from Cygwin for providing me with the power of the Linux tools in Windows
.PP
.TP
Erich Gamma and Kent Beck for developing with JUnit some kind of standard for unit testing
.PP
.TP
John Lakos, author of 'Large-Scale C++ Software Design'; after reading his book it was my first time writing unit tests
.PP

