.PP
.TH "Array" 3 "9 Nov 2002" "JsUnit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Array \- Standard ECMA class. 
.SH SYNOPSIS
.br
.PP
.SS "Public Methods"

.in +1c
.ti -1c
.RI "void \fBArray\fP ()"
.br
.ti -1c
.RI "Object \fBpop\fP ()"
.br
.RI "\fIPops last element from Array.\fP"
.ti -1c
.RI "Object \fBpush\fP ()"
.br
.RI "\fIPushes elements into Array.\fP"
.in -1c
.SH "DETAILED DESCRIPTION"
.PP 
Standard ECMA class.
.PP
.SH "CONSTRUCTOR & DESTRUCTOR DOCUMENTATION"
.PP 
.SS "void Array::Array ()"
.PP
.SH "MEMBER FUNCTION DOCUMENTATION"
.PP 
.SS "Object Array::pop ()"
.PP
Pops last element from Array.
.PP
The function is an implementation of the \fBArray::pop\fP method described in the ECMA standard. It removes the last element of the Array and returns it.
.PP
The function is active if the ECMA implementation does not implement it (like Microsoft JScript engine up to version 5.5). 
.PP
\fBReturns: \fP
.in +1c
Last element or undefined 
.SS "Object Array::push ()"
.PP
Pushes elements into Array.
.PP
The function is an implementation of the \fBArray::push\fP method described in the ECMA standard. It adds all given parameters at the end of the array.
.PP
The function is active if the ECMA implementation does not implement it (like Microsoft JScript engine up to version 5.5). 
.PP
\fBReturns: \fP
.in +1c
Number of added elements 

.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for JsUnit from the source code.
