.TH "CtxTestRunner" 3 "9 Nov 2002" "JsUnit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CtxTestRunner \- Class for an application running test suites with the BroadVision ctxdriver and console output. 
.SH SYNOPSIS
.br
.PP
Inherits \fBTextTestRunner\fP.
.PP
.SS "Public Methods"

.in +1c
.ti -1c
.RI "void \fBCtxTestRunner\fP ()"
.br
.ti -1c
.RI "void \fBwriteLn\fP (\fBString\fP str)"
.br
.RI "\fIWrite a line of text to the browser window.\fP"
.in -1c
.SH "DETAILED DESCRIPTION"
.PP 
Class for an application running test suites with the BroadVision ctxdriver and console output.
.PP
.SH "CONSTRUCTOR & DESTRUCTOR DOCUMENTATION"
.PP 
.SS "void CtxTestRunner::CtxTestRunner ()"
.PP
.SH "MEMBER FUNCTION DOCUMENTATION"
.PP 
.SS "void CtxTestRunner::writeLn (\fBString\fP str)"
.PP
Write a line of text to the browser window.
.PP
Parameters: \fP
.in +1c
.TP
\fB\fIstr\fP\fP
The text to print on the line. 

.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for JsUnit from the source code.
