.TH "JsUnitNSServer.js" 3 "9 Nov 2002" "JsUnit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JsUnitNSServer.js \- \fBTest\fP unit classes for a Netscape Server environment. 
.SH SYNOPSIS
.br
.PP
.SS "Compounds"

.in +1c
.ti -1c
.RI "class \fBNSServerTestRunner\fP"
.br
.RI "\fIClass for an application running test suites with a Netscape Server.\fP"
.in -1c
.SH "DETAILED DESCRIPTION"
.PP 
\fBTest\fP unit classes for a Netscape Server environment.
.PP
 This file contains extensions for the test unit framework especially for  output of the results at a Netscape Server.
.PP
.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for JsUnit from the source code.
