.TH "Protectable" 3 "9 Nov 2002" "JsUnit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Protectable \- A protectable can be run and throw an \fBError\fP. 
.SH SYNOPSIS
.br
.PP
.SS "Public Methods"

.in +1c
.ti -1c
.RI "virtual void \fBProtectable\fP ()"
.br
.ti -1c
.RI "virtual void \fBprotect\fP (\fBTest\fP test)"
.br
.RI "\fIRuns a test.\fP"
.in -1c
.SH "DETAILED DESCRIPTION"
.PP 
A protectable can be run and throw an \fBError\fP.
.PP
.SH "CONSTRUCTOR & DESTRUCTOR DOCUMENTATION"
.PP 
.SS "virtual void Protectable::Protectable ()\fC [virtual]\fP"
.PP
.SH "MEMBER FUNCTION DOCUMENTATION"
.PP 
.SS "virtual void Protectable::protect (\fBTest\fP test)\fC [virtual]\fP"
.PP
Runs a test.
.PP
Parameters: \fP
.in +1c
.TP
\fB\fItest\fP\fP
The test to run. 

.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for JsUnit from the source code.
