.TH "SystemWriter" 3 "9 Nov 2002" "JsUnit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemWriter \- The \fBPrinterWriter\fP of the JavaScript engine. 
.SH SYNOPSIS
.br
.PP
Inherits \fBPrinterWriter\fP.
.PP
.SS "Public Methods"

.in +1c
.ti -1c
.RI "void \fBSystemWriter\fP ()"
.br
.ti -1c
.RI "void \fB_flush\fP (void str)"
.br
.ti -1c
.RI "void \fBclose\fP ()"
.br
.RI "\fICloses the writer.\fP"
.in -1c
.SH "DETAILED DESCRIPTION"
.PP 
The \fBPrinterWriter\fP of the JavaScript engine.
.PP
.SH "CONSTRUCTOR & DESTRUCTOR DOCUMENTATION"
.PP 
.SS "void SystemWriter::SystemWriter ()"
.PP
.SH "MEMBER FUNCTION DOCUMENTATION"
.PP 
.SS "void SystemWriter::_flush (void str)"
.PP
Reimplemented from \fBPrinterWriter\fP.
.SS "void SystemWriter::close ()"
.PP
Closes the writer.
.PP
\fBFunction\fP just flushes the writer. Closing the system writer is not possible. 
.PP
Reimplemented from \fBPrinterWriter\fP.

.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for JsUnit from the source code.
