About Dojo
===================================

:Author: Dylan Schiemann
:Version: 0.2
:Copyright: Dojo Foundation, 2005
:Date: 2005/03/17

.. contents::

	
	
Roadmap
------------------------

Our current road map is to continue working on the plumbing and core components 
until we reach a point at which we can release something that people will find 
useful.  

This includes finishing the things described below in the current status 
(likely without much SVG support), and adding enough components and widgets to 
make the toolkit somewhat useful in addition to its core infrastructure.  If you 
have a widget or three that's preventing you from using Dojo, let us know.

The timeline for this release is mid-April, 2005 (FIXME: date needs to be verified)

Current Status
------------------------

Dojo is currently in development.  We have finished a significant portion of the
core "plumbing" for the project, and we also have our first widget, a button, 
that can be constructed from markup in HTML and SVG namespaces.  We have also shipped an `initial profile build`, and a supporting article, 
`baking usability into XMLHTTP`

We still have a lot of work to do on making our widget system better, 
especially in the world of SVG, but that will come later rather than sooner. 
The current SVG button could be described as 
hacky at best.  A button is a surprisingly complex widget, at least if it is 
done with any sort of sane flexibility and constraints.

Other things we are actively working on include our event, IO, and data binding
systems.  This makes Dojo an excellent toolkit for sending messages and data 
between the client and server, and between components in the client.
Ongoing improvements and refinements are being made to our xml declaration 
language (specifically to support contraints and state) and parser.  The parser
currently supports the most necessary markup constructs, with space to later accomodate more elaborate declaration mechanisms.

And of course, we're working on adding widgets that are useful.


Code Checkins
----------------

A complete list of checkins may be found through our `checkins mailing list`


Releases
------------------------

There are currently no release full builds available.  The
`dojo interest mailing list` contains regular updates.  `Anonymous SVN access` 
is available, as is an `initial profile build`.


Getting Involved
------------------------

Currently, contributors are added to the project through invitation only, much 
like firefox.  If you would like to contribute to the Dojo project, please 
contact us through the `dojo interest mailing list`.


License
-------

Dojo is licensed under the very friendly `Academic Free License v 2.1`. Some 
`thoughts on the AFL license` .

Dojo Foundation
---------------

Dojo is a California nonprofit corporation and is currently working on receiving 
tax exemption status.


.. FIXME: insert correct urls, and additional urls to make this more useful
.. _`checkins mailing list`: http://www.dojotoolkit.org/pipermail/dojo-checkins/
.. _`dojo interest mailing list`: http://www.dojotoolkit.org/pipermail/dojo-interest/
.. _`initial profile build` : http://dojotoolkit.org/dojo_browserio.tar.gz
.. _`baking usability into XMLHTTP` : http://dojotoolkit.org/intro_to_dojo_io.html
.. _`Anonymous SVN access` : http://dojotoolkit.org/svn/dojo/
.. _`Academic Free License v 2.1` : http://opensource.org/licenses/afl-2.1.php
.. _``thoughts on the AFL license` : http://netwindows.org/pipermail/ng-dhtml_netwindows.org/2005-January/000643.html

.. vim:ts=4:et:tw=0:shiftwidth=4:
