#!/usr/bin/perl

use Foundation;

echo("Running");

stopDojoOffline();
restoreSafariProxySettings();
restoreFirefoxProxySettings();
removeDefaults();
deleteFiles();

reportUninstalled();

exit 0;

sub stopDojoOffline{
	echo("Stopping Dojo Offline...");
	
	system "killall -9 dot";
	system "killall -9 proxy"
}

sub restoreSafariProxySettings{
	echo("Restoring Safari's proxy settings to "
			."what they were before Dojo Offline was installed...");
}

sub restoreFirefoxProxySettings{
	echo("Restoring Firefox's proxy settings to "
			."what they were before Dojo Offline was installed...");
			
	# get the old values from the defaults system
	
}

sub removeDefaults{
	echo("Removing Dojo Offline's default settings...");
}

sub deleteFiles{
	echo("Removing Dojo Offline files...");
}

sub reportUninstalled{
	$beSilent = false;
	
	# is this a silent uninstall?
	if(scalar(@ARGV) > 0){
		for($i = 0; $i < scalar(@ARGV); $i++){
			if(@ARGV[i] eq "--silent"){
				echo("Silent uninstall");
				$beSilent = true;
			}
		}
	}
	
	$msg = "Dojo Offline uninstalled.\n" .
			"Please restart Firefox and Safari for changes to take effect.";	
	echo($msg);
	
	if($beSilent eq false){
		# use a little bit of AppleScript magic to display a dialog telling the user
		# that uninstallation is done -- osascript is a command line utility to execute
		# AppleScript
		$runMe = "osascript " .
					"-e 'tell application \"Finder\"' " . 
		 				"-e 'activate' " .
						"-e 'display dialog \"$msg\" buttons [\"OK\"]' " .
					"-e 'end tell'";
		system($runMe);
	}
}

sub echo{
	my $msg = shift;
	$msg = "Uninstall: " . $msg;
	`echo "$msg" >> /tmp/dot_install.log 2>&1`;
	print "$msg\n";
}
