/* Generated By:JJTree: Do not edit this line. ASTOperator.java */

package org.dojo.jsl.parser;

import org.dojo.jsl.parser.EcmaScript;
import org.dojo.jsl.parser.EcmaScriptVisitor;

public class ASTOperator extends SimpleNode {
	private int operatorCode = EOF;

	public ASTOperator(int id) {
		super(id);
	}

	public ASTOperator(EcmaScript p, int id) {
		super(p, id);
	}

	/** Accept the visitor. * */
	@Override
	public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}

	// JMCL
	public void setOperator(int operatorCode) {
		this.operatorCode = operatorCode;
	}

	public int getOperator() {
		return operatorCode;
	}

	@Override
	public String toString() {
		return "Operator[" + tokenImage[operatorCode] + "]";
	}

}
