#!/bin/bash
cd ../src
if [ $# -gt 1 ]; then
	cd $2
fi
grep -r "dojo\.$1\." * | grep -v "\.svn" | grep -v dojo.require | grep -v dojo.provide | grep -v moduleLoaded | sed -r 's/^.*(dojo\.'$1'\.[a-zA-Z0-9_\.]+).*$/\1/' | sort | uniq -c | sort -g -r
