#!/bin/sh

echo "$SCRIPT_NAME: Running" >> ~/dot_install.log

# HACK: This is a phenomenal hack, but we need to find out
# the user that is running this installer; unfortunately
# we are 'root' right now because the installer authenticated
# us and there is no other way to find out who we are -- everything
# looks like root to us, including HOME. 
# So here's how we find out who we are:
# 	get a list of files being accessed by processes right now (lsof)
#	collapse multiple spaces into just one, to create consistent fields (tr)
# 	get a reference to our installer (grep)
# 	get the first one (head)
# 	the fifth field is our username (cut)
#
# TODO: Find something much less hacky and brittle than this
echo "$SCRIPT_NAME: Discovering what user is installing this..." >>~/dot_install.log 2>&1
userName=`lsof -n -P | tr -s ' ' | grep DojoOffline- | head -n 1  | cut -d ' ' -f3`
echo "$SCRIPT_NAME: User identified as $userName..." >>~/dot_install.log 2>&1

# copy our default PAC file to it's correct location
echo "$SCRIPT_NAME: Copying default PAC file over to user's home directory..." >>~/dot_install.log 2>&1
mv "/Applications/Dojo Offline Toolkit/.offline-pac $userName"

# copy our launch agent file over
echo "$SCRIPT_NAME: Copying launch agent file over..." >>~/dot_install.log 2>&1
mv "/Applications/Dojo Offline Toolkit/org.dojo.dot.DojoOfflineLaunchd.plist" $userName/Library/LaunchAgent

# start Dojo Offline up now
echo "$SCRIPT_NAME: Starting up Dojo Offline processes..." >>~/dot_install.log 2>&1
#su $userName
echo "$SCRIPT_NAME: whoami="`whoami` >>~/dot_install.log 2>&1
#nohup "/Applications/Dojo Offline Toolkit/dot" "/Applications/Dojo\ Offline\ Toolkit/"&

exit 0