#!/bin/sh
#
# Mac OS X's install system doesn't echo anything from our scripts into
# it's output when executed from the command-line 'installer' command,
# except for the VolumeCheck and the InstallationCheck scripts, so
# we manually append it to our own log file to aid debugging
#

echo "$SCRIPT_NAME: Running" >> /tmp/dot_install.log 2>&1

# stop the 'dot' and 'proxy' processes if they are running
echo "$SCRIPT_NAME: Stopping old 'dot' and 'proxy' processes..." >> /tmp/dot_install.log 2>&1

killall -9 dot
if test $? -eq 0; then
	echo "$SCRIPT_NAME: 'dot' process killed" >> /tmp/dot_install.log 2>&1
else
	echo "$SCRIPT_NAME: 'dot' process was not running" >> /tmp/dot_install.log 2>&1
fi

killall -9 proxy
if test $? -eq 0; then
	echo "$SCRIPT_NAME: 'proxy' process killed" >> /tmp/dot_install.log 2>&1
else
	echo "$SCRIPT_NAME: 'proxy' process was not running" >> /tmp/dot_install.log 2>&1
fi

# TODO: Make sure that System Preferences is not running.

exit 0