.TH "Function" 3 "9 Nov 2002" "JsUnit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Function \- Standard ECMA class. 
.SH SYNOPSIS
.br
.PP
.SS "Public Methods"

.in +1c
.ti -1c
.RI "void \fBFunction\fP ()"
.br
.ti -1c
.RI "void \fBfulfills\fP ()"
.br
.RI "\fIEnsures that a function fulfills an interface.\fP"
.in -1c
.SH "DETAILED DESCRIPTION"
.PP 
Standard ECMA class.
.PP
.SH "CONSTRUCTOR & DESTRUCTOR DOCUMENTATION"
.PP 
.SS "void Function::Function ()"
.PP
.SH "MEMBER FUNCTION DOCUMENTATION"
.PP 
.SS "void Function::fulfills ()"
.PP
Ensures that a function fulfills an interface.
.PP
Since with ECMA 262 (3rd edition) interfaces are not supported yet, this function will simulate the functionality. The arguments for the functions are all classes that the current class will implement. The function checks whether the current class fulfills the interface of the given classes or not. 
.PP
Exceptions: \fP
.in +1c
.TP
\fB\fI\fBTypeError\fP\fP\fP
 If the current object is not a class or the interface is not a Function object with a prototype. 
.TP
\fB\fI\fBInterfaceDefinitionError\fP\fP\fP
 If an interface is not fulfilled or the  interface has invalid members. 

.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for JsUnit from the source code.
