.TH "JsUnitBV.js" 3 "9 Nov 2002" "JsUnit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JsUnitBV.js \- \fBTest\fP unit classes for BroadVision environment. 
.SH SYNOPSIS
.br
.PP
.SS "Compounds"

.in +1c
.ti -1c
.RI "class \fBCtxTestRunner\fP"
.br
.RI "\fIClass for an application running test suites with the BroadVision ctxdriver and console output.\fP"
.in -1c
.SH "DETAILED DESCRIPTION"
.PP 
\fBTest\fP unit classes for BroadVision environment.
.PP
 This file contains extensions for the test unit framework especially  for BroadVision
.PP
.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for JsUnit from the source code.
