.TH "license" 3 "9 Nov 2002" "JsUnit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
license \- License
.PP
Copyright (c) 1999, 2000, 2001, 2002 by Jo\*'rg Schaible.
.PP
Test suites built with JsUnit are derivative works derived from tested classes and functions in their production; they are not affected by this license.
.PP
.SS "GNU GENERAL PUBLIC LICENSE"
.PP

