.TH "release" 3 "9 Nov 2002" "JsUnit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
release \- Release Notes
.PP
2002-09-20: Current release is version 1.2.beta.1
.PP
A lot of internal work has already be done. Most changes of JUnit 3.8.1 have been integrated and JsUnit is running quite smoothly for JScript, SpiderMonkey and Rhino. Also the new documentation script works fine.
.PP
Since the current state of the framework is now quite stable regading the mensioned JavaScript engines I will release an intermediate version 1.2 before version 2.0, that was proposed to have an integration with Edward Hieatt's browser GUI.
.PP
.SS "New Features"
.PP
.TP
\fBTest\fP is an interface now (conforming with JUnit), \fBTestCase\fP and  \fBTestSuite\fP implement this interface 
.TP
\fBAssert\fP supports member functions assertSame, assertTrue and  assertFalse 
.TP
\fBTestSuite\fP supports member function addTestSuite 
.TP
\fBTestResult\fP supports member function removeListener and  runProtected 
.TP
Support of class \fBResultPrinter\fP 
.TP
\fBBaseTestRunner\fP supports preferences 
.TP
Interface \fBProtectable\fP supported 
.TP
Support conforming \fBError\fP object hierarchy 
.TP
Alternative interface design contract by Function.fulfills 
.TP
New script for document generation recognizes functions and classes directly 
.TP
Support of the JUnit extension classes 
.TP
Changes of JUnit 3.8.1 and new classes migrated to JsUnit 
.TP
Special support in Assert.assertEquals comparing Strings or match a RegExp against a string 
.TP
New utility class \fBJsUtil\fP and enhanced \fBCallStack\fP API 
.TP
New utility class hierarchy \fBPrinterWriter\fP 
.TP
Special HTML support with classes \fBHTMLTestRunner\fP and  \fBHTMLWriterFilter\fP 
.PP
.SS "Design Changes"
.PP
.TP
JsUnit uses standard object model 
.TP
\fBTestSuite\fP supports again strings as name 
.TP
CallStack.js has been renamed to \fBJsUtil.js\fP 
.TP
Support of Array.push and Array.pop at all systems 
.TP
TestSuites for complete test files provided 
.TP
\fBTestSuite\fP needs now a TextCase object as argument 
.TP
\fBTestRunner\fP renamed to \fBBaseTestRunner\fP according to JUnit 
.TP
Call base class always with explicit name 
.TP
Name of fixtures are prepended with the name of the \fBTestCase\fP 
.TP
Native report format equals now JUnit. Old format supported by class ClassicReportPrinter 
.TP
Use TextTestRunner.prototype.main to call 
.PP
.SS "Bug Fixes"
.PP
.TP
Added BerliOS reference to project documentation 
.TP
Added test code for constructors 
.TP
HTML output of exceptions 
.TP
Expression 'this.constructor' does not refer direct base class 
.PP
.SS "Work in Progress"
.PP
.TP
 
.PP
.SH "ToDo List"
.PP 
  \fBTopic\fP \fBComment\fP  
.PP
Update compatibility list
.PP
Meanwhile I am aware of a lot more applications supporting JavaScript. Since most of the applications share the same JavaScript engine, I will introduce a grouping in the compatibility section of the documentation. Additionally I have to test the new JsUnit version for the supported platforms again and a compatibility check with the version 1.1 test cases should be done.
.PP
 
.PP
Integrate with JsUnit of Edward Hieatt
.PP
Edward's version of JsUnit is more based on a nice browser frontend. This would be also nice to have to my version. Edward and I agreed that I may try to integrate his GUI on top of my engine. Work currently stopped for version 1.2. Will be continued for JsUnit 2.0.
.PP
 
.PP
.SH "History of JsUnit"
.PP 
.SS "Version 1.1"
.PP
2001-09-07: Minor update
.PP

.SS "New Features"
.PP
.TP
Added unit tests for JsUnit library 
.TP
Automated test suite generation 
.TP
Browser \fBTestSuite\fP for JsUnit checks now JavaScript compatibility 
.TP
Support of Rhino and SpiderMonkey shells from Mozilla.org 
.TP
Support of Konqueror and Opera failed 
.PP

.SS "Design Changes"
.PP
.TP
\fBTestSuite\fP has no methods setUp and tearDown anymore 
.TP
BrowserTestRunner renamed to \fBHTMLTestRunner\fP 
.PP

.SS "Bug Fixes"
.PP
.TP
Added copyright notice to all files 
.TP
Added BerliOS reference to project documentation 
.TP
Corrected script tags in HTML files 
.TP
tearDown method was not called in case of an exception 
.PP
.SS "Version 1.0"
.PP
2001-08-01: Completing the library after more than a year more or less ongoing development, the first release of this software is published
.PP

.SS "Features"
.PP
.TP
Port of JUnit 3.2 for JavaScript 
.TP
Support of various systems, mostly based on standalone script  engines 
.TP
JavaDoc like documentation generation 
.PP

