.TH "StringWriter" 3 "9 Nov 2002" "JsUnit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StringWriter \- The \fBPrinterWriter\fP into a \fBString\fP. 
.SH SYNOPSIS
.br
.PP
Inherits \fBPrinterWriter\fP.
.PP
.SS "Public Methods"

.in +1c
.ti -1c
.RI "void \fBStringWriter\fP ()"
.br
.ti -1c
.RI "void \fB_flush\fP (void str)"
.br
.ti -1c
.RI "\fBString\fP \fBget\fP ()"
.br
.RI "\fIReturns the written \fBString\fP.\fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBmString\fP"
.br
.in -1c
.SH "DETAILED DESCRIPTION"
.PP 
The \fBPrinterWriter\fP into a \fBString\fP.
.PP
.SH "CONSTRUCTOR & DESTRUCTOR DOCUMENTATION"
.PP 
.SS "void StringWriter::StringWriter ()"
.PP
.SH "MEMBER FUNCTION DOCUMENTATION"
.PP 
.SS "void StringWriter::_flush (void str)"
.PP
Reimplemented from \fBPrinterWriter\fP.
.SS "\fBString\fP StringWriter::get ()"
.PP
Returns the written \fBString\fP.
.PP
The function will close also the stream if it is still open. 
.SH "MEMBER DATA DOCUMENTATION"
.PP 
.SS "int StringWriter::mString"
.PP


.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for JsUnit from the source code.
